export const personas = [
  {
    id: 'alex',
    name: 'Alex Rivera',
    cert: null,
    title: 'Aspiring PMP',
    pdus: { earned: 0, needed: 0 },
    renewalMonths: null,
    activePath: 'cert-prep',
    examDate: 'Sept 2025',
  },
  {
    id: 'jordan',
    name: 'Jordan S.',
    cert: 'PMP',
    title: 'Project Manager',
    pdus: { earned: 23, needed: 60 },
    renewalMonths: 14,
    activePath: 'cert-maintenance',
  },
  {
    id: 'sam',
    name: 'Sam Chen',
    cert: 'CAPM',
    title: 'Senior PM',
    pdus: { earned: 0, needed: 0 },
    renewalMonths: null,
    activePath: 'professional-edge',
  },
];

export const paths = [
  {
    id: 'cert-prep',
    label: 'Cert Prep',
    description: 'Your road to PMP exam day',
    steps: [
      'Eligibility check',
      'Exam application',
      'Study plan',
      'Practice exams',
      'Exam day',
    ],
    progress: { alex: 2, jordan: 5, sam: 5 },
  },
  {
    id: 'cert-maintenance',
    label: 'Cert Maintenance',
    description: 'Earn PDUs and keep your credential active',
    steps: [
      'Set PDU goal',
      'Complete education PDUs',
      'Giving back PDUs',
      'Submit renewal',
    ],
    progress: { alex: 0, jordan: 2, sam: 0 },
  },
  {
    id: 'professional-edge',
    label: 'Professional Edge',
    description: 'Stay sharp and grow beyond the cert',
    steps: [
      'Explore trending topics',
      'Join a webinar',
      'Complete a skill module',
      'Engage with community',
    ],
    progress: { alex: 0, jordan: 1, sam: 2 },
  },
];

export const content = [
  {
    id: 1,
    type: 'course',
    format: 'On-demand',
    duration: '4h',
    topic: 'AI',
    title: 'AI for Project Managers',
    description: 'How to apply AI tools to planning, risk, and reporting',
  },
  {
    id: 2,
    type: 'webinar',
    format: 'Live',
    duration: '1h',
    topic: 'Leadership',
    title: 'Stakeholder Communication in Hybrid Teams',
    description: 'Practical strategies for distributed project leadership',
  },
  {
    id: 3,
    type: 'bite-size',
    format: 'Article',
    duration: '8 min',
    topic: 'Agile',
    title: 'Kanban vs Scrum: Which fits your team?',
    description: 'A quick breakdown of when to use each framework',
  },
  {
    id: 4,
    type: 'course',
    format: 'On-demand',
    duration: '6h',
    topic: 'Risk',
    title: 'Risk Management Fundamentals',
    description: 'Core frameworks for identifying and mitigating project risk',
  },
  {
    id: 5,
    type: 'webinar',
    format: 'Live',
    duration: '90 min',
    topic: 'AI',
    title: 'Generative AI in the PMO',
    description: 'Real use cases from PMOs already using AI in their workflows',
  },
  {
    id: 6,
    type: 'bite-size',
    format: 'Video',
    duration: '5 min',
    topic: 'Leadership',
    title: 'Running Better Retrospectives',
    description: 'One technique to make your retros actually actionable',
  },
  {
    id: 7,
    type: 'course',
    format: 'On-demand',
    duration: '3h',
    topic: 'Agile',
    title: 'Scaling Agile Across the Enterprise',
    description: 'SAFe, LeSS, and when to use which scaling approach',
  },
  {
    id: 8,
    type: 'webinar',
    format: 'On-demand',
    duration: '1h',
    topic: 'Sustainability',
    title: 'Sustainable Project Management',
    description: 'Embedding ESG thinking into project delivery',
  },
  {
    id: 9,
    type: 'bite-size',
    format: 'Article',
    duration: '6 min',
    topic: 'AI',
    title: 'Prompting for PMs: A Starter Guide',
    description: 'Five prompt patterns that save project managers hours each week',
  },
  {
    id: 10,
    type: 'course',
    format: 'On-demand',
    duration: '5h',
    topic: 'Leadership',
    title: 'Negotiation Skills for Project Leaders',
    description: 'Influence without authority across stakeholders and vendors',
  },
];
